version: '3.9'

services:
api:
  container_name: stoke_api
  build: .
  ports:
    - 3000:3000
  environment:
    - DB_HOST=db
    - DB_PASSWORD=1234
    - DB=stoke_db
    - DB_USER=mateu
    - SECRET_KEY=77888393
  depends_on:
  db:
    condition: service_healthy
  volumes:
    - .:/app

db:
  container_name: db
  image: postgres:14
  ports:
    - 5431:5432
  environment:
    - POSTGRES_USER=mateu
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=stoke_db
  healthcheck:
  test: ['CMD-SHELL', 'pg_isready -U mateu -d stoke_db']
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 5s

  volumes:
    - postgres_stoke_api:/var/lib/postgresql/data

volumes:
  postgres_stoke_api:
    driver: local
