version: "3.9"

services:
  api:
    container_name: stoke_api
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_USER=anthoni
      - DB_PASSWORD=1234
      - DB_HOST=stoke_db
      - DB=stoke_db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: stoke_db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=anthoni
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=stoke_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anthoni -d stoke_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - stoke_api:/var/lib/postgresql/data

volumes:
  stoke_api:
    driver: local
