version: '3.9'

services:
  api:
    container_name: stoke_api
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000

      - DB_USER=process.env.DB_USER
      - DB_PASSWORD=process.env.DB_PASSWORD
      - DB_HOST=process.env.DB_HOST
      - DB=process.env.DB

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: stoke_db
    image: postgres:14
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - stoke_api:/var/lib/postgresql/data

volumes:
  stoke_api:
    driver: local
